---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: "bundle exec rake validate && bundle exec rake test SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.1.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.1.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.2.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.4.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES="yes"
notifications:
  email: false
  hipchat:
    rooms:
      - secure: "aRJ187uJZQ8JtMyFZbcDXTpgMUCkcs0gY3sn/uzowZIAKLXECvHE43rG5/VWBC9uWrv5d4q5U8AANPgVZpBZyt9UUFR9FSXRtd3skuP/SqS4nt31SlF52lWiq0dFje/mpuBvAsoV3xD/nQgIzxPT/sWfDlpGHF5TvLG8AXbFrKU="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
  on_success: always
  on_failure: always
